channels:
- conda-forge
- defaults
dependencies:
- cxx-compiler
- GDAL!=3.6.*,!=3.7.*
- GDAL>=3.4.2
- libsqlite<3.49.1
- libxcrypt
- nomkl
- python=3.9
- sqlite<3.49.1
- pip:
  - Babel
  - build  # pip-only
  - chardet>=3.0.4
  - coverage
  - Flask
  - flask_cors
  - geometamaker
  - numpy>=1.11.0,!=1.16.0
  - pandas>=1.2.1
  - pint
  - psutil>=5.6.6
  - pygeoprocessing>=2.4.6
  - PyInstaller>=6.9.0
  - Pyro5
  - pytest
  - pytest-subtests!=0.14.0  # https://github.com/pytest-dev/pytest-subtests/issues/173
  - requests
  - rst2html5
  - Rtree>=0.8.2,!=0.9.1
  - scipy>=1.9.0,!=1.12.*
  - setuptools>=8.0,!=60.7.0
  - setuptools_scm
  - setuptools_scm>=6.4.0
  - shapely>=2.0.0
  - taskgraph>=0.11.0
  - virtualenv>=12.0.1
  - wheel>=0.27.0
  - xlwt
