name: Build Example App Binaries

on:
    push:
    pull_request:

jobs:
    build-mac-binaries:
        name: "Build mac binaries"
        runs-on: macos-10.15
        env:
            PYTHON_VERSION: 3.8
            PYTHON_ARCH: x64
        steps:
            - uses: actions/checkout@v2

            - name: Setup conda environment
              uses: conda-incubator/setup-miniconda@v2
              with:
                  activate-environment: macbin-env
                  auto-update-conda: true
                  python-version: 3.8
                  channels: conda-forge

            - name: Build conda env with python dependencies
              shell: bash -l {0}
              run: |
                  conda upgrade -y pip setuptools
                  conda install wheel
                  pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
                  pip install qtpy>1.3 PySide2!=5.15.0 dmgbuild

            - name: Build binaries
              shell: bash -l {0}
              run: |
                  # print out env info
                  conda list

                  # make python packages
                  python3 setup.py bdist_wheel

                  # install
                  rm -r example.egg-info
                  python3 -m pip install --isolated --upgrade --no-index --only-binary example --find-links=dist example

                  # make binaries
                  python3 -m PyInstaller --workpath build/pyi-build --clean --distpath dist/ --noupx example.spec

                  # make mac app bundle
                  ./build_app_bundle.sh
                  
                  # make dmg
                  dmgbuild -Dexampledir="build/mac_app/ExampleApp.app" -s "dmgconf.py" "ExampleApp" "dist/ExampleApp.dmg"


            - name: Upload DMG artifact
              uses: actions/upload-artifact@v2-preview
              with:
                  name: ExampleApp-dmg
                  path: dist/ExampleApp.dmg

  