name: Build InVEST App Binaries

on:
    push:
    pull_request:

jobs:
    check-syntax-errors:
        name: "Check for syntax errors"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up python 3.8
              uses: actions/setup-python@v1
              with:
                  python-version: 3.8

            - name: Set up environment
              run: python -m pip install --upgrade flake8

            - name: Lint with flake8
              run: |
                # stop the build if there are Python syntax errors or undefined names
                python -m flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
                # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                python -m flake8 src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    build-mac-binaries:
        name: "Build mac binaries"
        needs: check-syntax-errors
        runs-on: macos-10.15
        env:
            PYTHON_VERSION: 3.8
            PYTHON_ARCH: x64
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0  # fetch complete history

            - name: Fetch git tags
              run: git fetch origin +refs/tags/*:refs/tags/*

            - name: Restore conda cache
              uses: actions/cache@v2
              with:
                  path: ~/opt/anaconda3
                  key: mac-py${{ env.PYTHON_VERSION }}-${{ env.PYTHON_ARCH}}-conda-${{ hashFiles('**/requirements*.txt') }}-exe

            - name: Setup conda environment
              uses: conda-incubator/setup-miniconda@v2
              with:
                  activate-environment: macbin-env
                  auto-update-conda: true
                  python-version: 3.8
                  channels: conda-forge

            - name: Build conda env with python dependencies
              shell: bash -l {0}
              run: |
                  conda upgrade -y pip setuptools
                  conda install wheel setuptools_scm PyInstaller
                  pip install qtpy>1.3
                  pip install qtawesome
                  pip install PySide2!=5.15.0
                  pip install dmgbuild

            - name: Build binaries
              shell: bash -l {0}
              run: |
                  make install
                  make mac_dmg

            - name: Upload DMG artifact
              uses: actions/upload-artifact@v2-preview
              with:
                  name: InVEST-dmg
                  path: dist/InVEST*.dmg

  