name: Run Tests and Build

on: [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

concurrency:
  # make sure only one run of this workflow for a given PR or a given branch
  # can happen at one time. previous queued or started runs will be cancelled.
  # github.workflow is the workflow name
  # github.ref is the ref that triggered the workflow run
  # on push, this is refs/heads/<branch name>
  # on pull request, this is refs/pull/<pull request number>/merge
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # build: dependency of make install
  # nomkl: make sure numpy w/out mkl
  # setuptools_scm: needed for versioning to work
  CONDA_DEFAULT_DEPENDENCIES: python-build nomkl setuptools_scm
  LATEST_SUPPORTED_PYTHON_VERSION: "3.12"

jobs:

  build-binaries:
    name: Build binaries
    runs-on: windows-latest
    steps:

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Restore node_modules cache
        id: nodemodules-cache
        uses: actions/cache@v3
        with:
          path: workbench/node_modules
          key: windows-latest-${{ runner.arch }}-${{ hashFiles('workbench/yarn.lock') }}

      - name: Download micromamba for distribution (Windows)
        shell: pwsh
        run: |
          Invoke-Webrequest -URI https://micro.mamba.pm/api/micromamba/win-64/2.0.4 -OutFile micromamba.tar.bz2
          tar xf micromamba.tar.bz2
          MOVE -Force Library\bin\micromamba.exe .\micromamba.exe
          .\micromamba.exe --help  # make sure the executable works

      - run: |
          micromamba.exe create --yes --prefix ./test_env -c conda-forge python pip==24.2
          micromamba.exe run --prefix ./test_env python -m pip --version
          micromamba.exe run --prefix ./test_env pip --version

