name: Run Test

on: [push, pull_request]

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
      volumes:
        - /home/runner/work/invest/invest:/__w/invest/invest
    strategy:
      fail-fast: false
      matrix:
        container: [quay.io/pypa/manylinux_2_28_x86_64, 'amd64/almalinux:9', 'ubuntu:latest', '']
    steps:
      - name: test
        run: |
          pwd
          ls

          mkdir foo
          ls -ld foo
          chmod 0444 foo
          ls -ld foo
          cd foo
